---
    name: CI
    
    on: # yamllint disable-line rule:truthy
      push:
        branches: [main]
      pull_request:
        branches: [main]
    
    concurrency:
      group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
      cancel-in-progress: true

    jobs:
        lint-test:
            name: Lint and Test
            runs-on: ubuntu-22.04
            strategy:
              matrix:
                python-version: ["3.11"]

            steps:
                - uses: actions/checkout@v4
                - name: Install UV
                  run: pipx install uv

                - name: Set up Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: ${{ matrix.python-version }}

                - name: Display Python version
                  run: python -c "import sys; print(sys.version)"

                - name: Build uv lock file
                  run: uv lock

                  # Github Actions can't see Artifactory so remove it from pyproject.toml,
                  # set the default index back to pypi, then re-lock and sync
                - name: Setup and install dependencies
                  run: |
                    sed -i '/\[tool.uv\]/,/^\s*$/d' pyproject.toml
                    sed -i '/\[\[tool.uv.index\]\]/,/^\s*$/d' pyproject.toml
                    uv lock --default-index https://pypi.org/simple
                    uv sync

                - name: Install dependencies
                  run: uv sync
  
                - name: check code formatting
                  run: make check-python-nofix

                - name: Cleanup residue file
                  run: make clean

                - name: setup gitleaks
                  run: make setup-gitleaks
                
                - name: run gitleaks
                  run: make run-gitleaks

    
    